name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-checking:
    name: Lint checking
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: astral-sh/ruff-action@v2

  build:
    name: Build tool
    runs-on: ${{ matrix.os }}
    needs: lint-checking

    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        python-version:
          - "3.12"
        poetry-version:
          - "latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/prepare-workspace
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ matrix.poetry-version }}
          os: ${{ matrix.os }}

      - name: Run tests
        run: poetry run pytest -v

      - name: Check build artifacts
        run: poetry build
