name: PyPI Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/prepare-workspace
        with:
          python-version: "3.12"
          os: "ubuntu-latest"

      - name: Check publish token set
        run: |
          if ! [ -n "${{secrets.PYPI_API_TOKEN}}" ]; then exit 1; fi

      - name: Publish to PyPI
        run: |
          poetry config pypi-token.pypi "${{secrets.PYPI_API_TOKEN}}"
          poetry publish --build
