name: PyPI Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/prepare-workspace
        with:
          python-version: "3.12"
          os: "ubuntu-latest"

      - name: Get package version
        run: |
          TAG=$(git describe HEAD --tags)
          PROJECT_VERSION=$(poetry version --short)
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
          if [[ "$TAG" != "v$PROJECT_VERSION" ]]; then exit 1; fi

      - name: Check publish token set
        run: |
          if ! [ -n "${{secrets.PYPI_API_TOKEN}}" ]; then exit 1; fi

      - name: Publish to PyPI
        run: |
          poetry config pypi-token.pypi "${{secrets.PYPI_API_TOKEN}}"
          poetry publish --build
