name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  autorelease:
    name: Create Release
    runs-on: "ubuntu-latest"

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/prepare-workspace
        with:
          python-version: "3.12"
          os: "ubuntu-latest"

      - name: Get package version
        run: |
          TAG=$(git describe HEAD --tags --abbrev=0)
          PROJECT_VERSION=$(git describe HEAD --tags)
          PROJECT_VERSION="${PROJECT_VERSION#v}"
          echo "Version: $PROJECT_VERSION"
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
          # if [[ "$TAG" != "$PROJECT_VERSION" ]]; then exit 1; fi
  
      - name: Run tests
        run: poetry run pytest -v

      - name: Build
        run: PROJECT_VERSION="${{ env.PROJECT_VERSION }}" poetry build

      - name: Release Notes
        run: git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n  * %an <%ae>' --no-merges >> ".github/RELEASE-TEMPLATE.md"

      - name: Create Release Draft
        uses: softprops/action-gh-release@v2
        with:
          body_path: ".github/RELEASE-TEMPLATE.md"
          draft: true
          files: |
            dist/nats_app-${{ env.PROJECT_VERSION }}-py3-none-any.whl
            dist/nats_app-${{ env.PROJECT_VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
