name: Build and Publish to TestPyPI

on: [ workflow_dispatch ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch tags
        run: |
          git fetch --prune --unshallow --tags

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - run: poetry install

      - run: poetry config repositories.test-pypi https://test.pypi.org/legacy/
      - run: poetry config pypi-token.test-pypi "${{ secrets.TEST_PYPI_API_TOKEN }}"

      - name: Get package version
        run: |
          TAG=$(git describe HEAD --tags --abbrev=0)
          PROJECT_VERSION=$(git describe HEAD --tags)
          PROJECT_VERSION="${PROJECT_VERSION#v}"
          echo "Version: $PROJECT_VERSION"
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
          # if [[ "$TAG" != "$PROJECT_VERSION" ]]; then exit 1; fi

      - name: Publish package
        run: PROJECT_VERSION="${{ env.PROJECT_VERSION }}" poetry publish --build -r test-pypi
